name: Deploy ShopApp to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t harshvishwakarma/shopapp .
          docker tag harshvishwakarma/shopapp harshvishwakarma/shopapp:latest
          docker push harshvishwakarma/shopapp:latest

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull harshvishwakarma/shopapp:latest
          docker stop shopapp || true
          docker rm shopapp || true
          docker run -d -p 80:3000 --name shopapp harshvishwakarma/shopapp:latest
          EOF
