name: Deploy ShopApp to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t mydockerhubuser/Shopapp .
          docker tag mydockerhubuser/Shopapp mydockerhubuser/Shopapp:latest
          docker push mydockerhubuser/Shopapp:latest

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull mydockerhubuser/Shopapp:latest
          docker stop Shopapp || true
          docker rm Shopapp || true
          docker run -d -p 80:3000 --name Shopapp mydockerhubuser/Shopapp:latest
          EOF
